apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multivpc-eni-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multivpc-eni-agent
subjects:
  - kind: ServiceAccount
    name: multivpc-eni-agent
    namespace: {{ .Release.Namespace }}
