apiVersion: v1
kind: ConfigMap
metadata:
  name: multivpc-eni-agent
  labels:
    app.kubernetes.io/name: multus-multivpc-cni
data:
  network-profiles.yaml: |
{{- if .Values.networkProfiles }}
{{ toYaml (dict "networkProfiles" .Values.networkProfiles) | indent 4 }}
{{- else }}
    networkProfiles: {}
{{- end }}
