apiVersion: v1
kind: ServiceAccount
metadata:
  name: multivpc-eni-agent
  labels:
    app.kubernetes.io/name: multus-multivpc-cni
  {{- if .Values.nodeAgent.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.nodeAgent.iamRoleArn | quote }}
  {{- end }}
